search:
  algorithm: mcts
  algorithm_config:
    C: 1.4
    default_prior: 0.5
    use_prior: True
    prune_cycles_in_search: True
    search_rewards:
      - state score
  max_transforms: 6
  iteration_limit: 100
  return_first: false
  time_limit: 120
  exclude_target_from_stock: True
  # break_bonds: [[1, 2], [2, 3]] Уберем, вызывает ошибку на 3 молекуле
  # freeze_bonds: [[3, 4]]
  break_bonds_operator: or
expansion:
  uspto:
    - /Users/evgondar/Desktop/тестовое/aizynth_data/uspto_model.onnx
    - /Users/evgondar/Desktop/тестовое/aizynth_data/uspto_templates.csv.gz
  ringbreaker:
    - /Users/evgondar/Desktop/тестовое/aizynth_data/uspto_ringbreaker_model.onnx
    - /Users/evgondar/Desktop/тестовое/aizynth_data/uspto_ringbreaker_templates.csv.gz
filter:
  uspto: /Users/evgondar/Desktop/тестовое/aizynth_data/uspto_filter_model.onnx
stock:
  zinc: /Users/evgondar/Desktop/тестовое/aizynth_data/zinc_stock.hdf5


